import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "./components/NavBar";
import { UserProvider } from "./contexts/UserContext";
import { CartProvider } from "./contexts/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
        <body>
          <UserProvider>
            <CartProvider>
              {/* Layout UI */}
              <NavBar />
              <main>{children}</main>
            </CartProvider>
          </UserProvider>
        </body> 
    </html>
  );
}
